### ISSUE TITLE
Upgrade contracts to Cairo2.7.0 syntax

### ISSUE THREAD

**Issue by Goodness5** [Custos-Diretriz/custos-starknet#3]
The agreement and crime_records contracts are still in the old syntax, update these contracts and the entire codebase to the latest Cairo syntax.

**Comment by casweeney** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.

### How I plan on tackling this issue
Looking at the `Agreement` contract, I can see that some old version syntax are still in the code base. Example, the use of `LegacyMap` instead of `Map`. I will rewrite the entire codebase to use the latest cairo syntax.

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged

I am a Blockchain developer with expertise in Cairo, Solidity, Rust, and Foundry. I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge

### How I plan on tackling this issue
I would review the current contracts and familiarize myself with the changes in Cairo2.7.0. Then, I'd update the contracts accordingly and run thorough tests

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a frontend and a starknet developer.

### How I plan on tackling this issue


1. Understand Version Changes:
I’ll begin by familiarizing myself with the differences between the old Cairo version and the latest one, especially focusing on syntax, functions, and imports.


2. Set Up My Environment:
I’ll ensure I have the latest version of Cairo installed and confirm that my tools (StarkNet CLI, Protostar, IDE plugins) are compatible with the updated version.


3. Identify Contracts to Update:
I’ll list all the contracts and files that need to be updated, such as the agreement and crime_records contracts, so I can track my progress.


4. Refactor Gradually:
I’ll start small, updating one contract or function at a time to avoid overwhelming changes. I’ll begin with the agreement contract.


5. Update Structs and Functions:
For each contract, I’ll:

Update struct definitions to the new syntax.

Change function definitions to the new style.

Replace felt with felt252.



6. Run Tests After Each Change:
After updating a part of the contract, I’ll run tests to ensure everything works smoothly before proceeding.


7. Refactor the Entire Codebase:
Once I’ve updated all contracts, I’ll refactor any repetitive code and optimize using the new Cairo features.


8. Handle Dependencies:
I’ll make sure that any external libraries or contracts my code depends on are also updated.


9. Final Testing and Deployment:
After all changes, I’ll run tests, deploy to a testnet, and ensure everything is functioning as expected in a live environment.




---

This step-by-step plan will help me update the contracts efficiently while ensuring correctness along the way.

**Comment by OkoliEvans** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hey @Goodness5 , I will love to take up this issue. I have been contributing to Open Source projects on Starknet via OnlyDust, especially on projects where Cairo smart contract expertise were required.

**Comment by casweeney** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.

### How I plan on tackling this issue
I can already see that the `Storage` struct in both `Agreement` and `CrimeRecord` contract are still using `LegacyMap` instead of `Map`. I will rewrite the entire `Agreement` and `CrimeRecord` using the latest Cairo syntax, as I have already read through the contract and I pretty much understand the codebase.

Also with my vast understanding of components in Cairo, I will update the components implementation in the `CrimeRecord` contract to use the latest version of openzeppelin components (`ERC721Component`, `OwnableComponent`, `UpgradeableComponent` and `SRC5Component`).

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello! My name is Lukman, a passionate Smart Contract Developer with 2 years of experience writing smart contracts. I have hands-on experience spans various blockchain platforms, including Ethereum and Starknet. 

### How I plan on tackling this issue
To approach this issue, I will start by thoroughly reviewing the official Cairo documentation and release notes to understand the key changes and new features introduced in this version. Additionally, I will leverage community resources, such as forums and tutorials, to gain insights and best practices for implementing the necessary updates efficiently.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### How I plan on tackling this issue
I will update the entire codebase to Cairo 2.7.0 by first updating the dependencies in Scarb.toml and ensuring compatibility with the latest OpenZeppelin versions. The core work involves updating the syntax patterns, including storage declarations, component declarations, and event handling to use the new attribute-based syntax. I'll implement new error handling patterns and modernize the code with new array syntax and storage access patterns. Testing files will be updated to maintain compatibility. To ensure clean version control, I'll create separate PRs for each contract upgrade. The upgrade process will be completed in 2 days, focusing on systematic updates and verification of functionality.

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I'll update the syntax and ensure, the changes don't break the code and all already existing tests are passing.

**Comment by GideonBature** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Software Engineer and Open-source contributor, with experience in Rust, JavaScript, TypeScript and of recent Cairo. I have participated the in the last two ODhack and have made considerable contribution to the Starknet Ecosystem. I have written various contracts with the latest Cairo syntax, hence I will be able to update the `crime_records` and `agreement` contracts to the most recent Cairo syntax.

### How I plan on tackling this issue
To solve this task, I am going to start by first testing the contracts to see how the whole code works, afterwards I am going to go through each contracts (although I have done that already) and identify all the Syntax that are redundant/old, then re-implement the latest version of those syntax, after which I am going to test the contracts to make sure everything is still working fine just as how I tested it before making any changes.

**Comment by Goodness5** [comment]
@OkoliEvans there's an issue that depends on this particular issue so the person assigned to it needs you to finish up faster so he can work on his issue 
hope you're fine with that

**Comment by OkoliEvans** [comment]
Yeah 👍 @Goodness5
